import Header from '@/app/components/auth/Header';
import RouteGuard from '@/app/components/auth/RouteGuard';

export const metadata = {
   title: 'login and signup layout',
   description: 'Generated by create next app',
};

export default function AuthLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <>
         <RouteGuard type="auth" />
         <Header />
         {children}
      </>
   );
}
